model:
  backbone:
    config: mit_b1
    stride:
    - 4
    - 2
    - 2
    - 1
  label_feature_path: medclip/bcss_label_fea
  knowledge_feature_path: clinical_bert/bcss_knowledge_fea
  n_ratio: 0.5
dataset:
  name: bcss
  train_root: /project/hnguyen2/mvu9/datasets/weakly_sup_segmentation_datasets/BCSS-WSSS/training
  val_root: /project/hnguyen2/mvu9/folder_04_ma/WSSS-01/src/externals/TPRO/data/BCSS-WSSS
  cls_num_classes: 4
  input_size:
  - 224
  - 224
work_dir:
  ckpt_dir: /project/hnguyen2/mvu9/wsss_workingdir/ckpt_dir/classification
  pred_dir: /project/hnguyen2/mvu9/wsss_workingdir/predictions/classification
  train_log_dir: /project/hnguyen2/mvu9/wsss_workingdir/train_log/classification
train:
  samples_per_gpu: 10
  epoch: 8
  pretrained: true
  l1: 0.0
  l2: 0.1
  l3: 1.0
  l4: 1.0
optimizer:
  type: AdamW
  learning_rate: 0.0001
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.001
scheduler:
  warmup_iter: 0
  warmup_ratio: 1.0e-06
  power: 1.0
